### ISSUE TITLE
Поправить отображение предметов преподавателя в поиске

### ISSUE THREAD

**Issue by BatuevIO** [profcomff/rating-ui#16]
Сейчас если у преподавателя много предметов, то появляется листалка, на которую нельзя нажать без проваливания в страницу преподавателя. Поправить можно одним из двух способов: 
- Починить кнопки, то есть сделать так, что при нажатии на них не происходит нажатия на карточку.
- Оставить только 1-2 отображаемых предмета, а остальные скрыть в виде (+N)

**Comment by Dmatrushka19** [comment]
Оставил второй вариант, теперь отображается максимум два предмета, остальные сворачиваются в плашку "еще n" (см. скрин). Замерджил в основную ветку.
![Снимок экрана 2024-11-25 224804](https://github.com/user-attachments/assets/47c55df6-8cc6-4fde-bad5-aa5155d356c5)
