### ISSUE TITLE
Сохранять параметры поиска и номер просматриваемой страницы при возвращении со страницы лектора

### ISSUE THREAD

**Issue by BatuevIO** [profcomff/rating-ui#26]
Сейчас если нажать "назад к поиску" на странице лектора, то все параметры поиска сбрасываются и открывается первая страница. Можно сохранять эти параметры и открывать страницу поиска с ними.

**Comment by Dmatrushka19** [comment]
Нужно хранить 5 компонент:
1) строку поиска
2) сортировку по предмету
3) сортировку по доброте/халявности...
4) номер страницы, откуда был переход
5) сортировку от А до Я, от Я до А

Завести стор, 4 поля и две функции:
getParams -> возвращает 4 поля, будет вызываться, когда вернулся со страницы лектора
satParams -> по заданным значениям сетит 4 поля, будет вызываться перед тем, как уйти на другую страницу
deleteParams -> при выходе из дубинушки, параметры должны чиститься (?)
